jnsdev:
  client:
    address:
      url: http://address.mocklab.io/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
  cloud:
    config:
      enabled: false